### ISSUE TITLE
Doesn't work with the retail version

### ISSUE THREAD

**Issue by georgeli94** [poulader/HitmanBloodMoney_UnlimitedSaves#1]
I have the Steam version and it works well, but if I try using it with the retail version, it crashes. I prefer using the retail version as the one I got off the Hitman Collection CD is DRM free, but it's not compatible with the unlimited saves patch. Any plans on updating this to make it compatible with the retail version?

**Comment by ZeGatoSupreme** [comment]
Can you send me the retail exe

**Comment by poulader** [comment]
Can you send me the exe from retail

**Comment by georgeli94** [comment]
https://www.dropbox.com/s/wyjzal3rs092q26/HitmanBloodMoney.exe?dl=0

Here's a Dropbox link. Thank you.

**Comment by poulader** [comment]
Can you try this version and lmk if it works please, thanks.

https://github.com/poulader/HitmanBloodMoney_UnlimitedSaves/releases/tag/1.0.3

**Comment by georgeli94** [comment]
Sorry for the late reply. Was busy for the past week.

I'm getting a "could not find load pattern" error.

**Comment by poulader** [comment]
Hey there

I missed a small difference in opcodes between steam and retail for pro load patching, it should be fixed now. Please try this release https://github.com/poulader/HitmanBloodMoney_UnlimitedSaves/releases/tag/1.0.4

Regarding contracts, once I finish my current playthrough of blood money, I may load up contracts and take a look at it.

**Comment by poulader** [comment]
Hey there

I missed a slight difference in opcodes between retail and steam, plus memory access protections needed to be set in retail.

I tested on both steam/retail, this version works, please lmk either way how it goes for you.

https://github.com/poulader/HitmanBloodMoney_UnlimitedSaves/releases/tag/1.0.5

As far as contracts, once I finish my current blood money session, I may take a look at it again.

Cheers

**Comment by georgeli94** [comment]
Thank you very much, it finally works.

As for Contracts, someone else figured out how to Hex Edit Contracts to give 240 saves per level. I'd figure if I can't beat a mission with 240 saves, I just suck too much to play Hitman, so I settled for that. Blood Money was the only one that wasn't working for me and you finally fixed it. Thanks.
